### ISSUE TITLE
Isometric Camera For Stars

### ISSUE THREAD

**Issue by xAmaranth** [irisong980912/polaris#93]
The camera should move to a static position when players are in a solar system.

The chase-camera should move smoothly into place when the player enters the solar system, and should being chasing the player again when they leave the system.

**Movement does not need to be implemented! Only the camera behaviour needs to be done. Refer to issue #94 **

**Comment by xAmaranth** [comment]
Careful consideration is needed in determining where to put the camera for each solar system. Ideally, the camera should look along the axis of rotation of the system, so players have an _almost_ top-down view of the system.

**Comment by irisong980912** [comment]
Implementation changed: the isometric camera starts when player starts orbiting the planet. 

Go to isometric view as soon as the player enters the solar system will take out a lot of the aesthetic fun of the game. Players are unable to see the star and planet models clearly nor can they observe the animation in detail. I playtested this with my roommate and she said it is boring. 

Since the isometric view is purposed for the guided slingshot, we should only turn the camera to isometric view once the player start orbiting the planet.
